[2024-06-16 01:06:57 +0300] [8017] [INFO] Starting gunicorn 22.0.0
[2024-06-16 01:06:57 +0300] [8017] [INFO] Listening at: http://127.0.0.1:5000 (8017)
[2024-06-16 01:06:57 +0300] [8017] [INFO] Using worker: sync
[2024-06-16 01:06:57 +0300] [8019] [INFO] Booting worker with pid: 8019
[2024-06-19 08:29:30,130] ERROR in app: Exception on /checkreview/18 [GET]
Traceback (most recent call last):
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/app/app.py", line 125, in check_review
    rew_lenth = len(reviews)
                ^^^^^^^^^^^^
TypeError: object of type 'function' has no len()
[2024-06-19 08:29:34,962] ERROR in app: Exception on /checkreview/18 [GET]
Traceback (most recent call last):
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/app/app.py", line 125, in check_review
    rew_lenth = len(reviews)
                ^^^^^^^^^^^^
TypeError: object of type 'function' has no len()
[2024-06-19 08:30:30,167] ERROR in app: Exception on /checkreview/18 [GET]
Traceback (most recent call last):
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/app/app.py", line 125, in check_review
    rew_lenth = len(reviews)
                ^^^^^^^^^^^^
TypeError: object of type 'function' has no len()
[2024-06-19 08:30:38,334] ERROR in app: Exception on /checkreview/18 [GET]
Traceback (most recent call last):
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/app/app.py", line 125, in check_review
    rew_lenth = len(reviews)
                ^^^^^^^^^^^^
TypeError: object of type 'function' has no len()
[2024-06-19 08:42:11,955] ERROR in app: Exception on /checkreview/18 [GET]
Traceback (most recent call last):
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/app/app.py", line 125, in check_review
    rew_lenth = len(reviews)
                ^^^^^^^^^^^^
TypeError: object of type 'function' has no len()
[2024-06-19 08:42:14,613] ERROR in app: Exception on /checkreview/19 [GET]
Traceback (most recent call last):
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/app/app.py", line 125, in check_review
    rew_lenth = len(reviews)
                ^^^^^^^^^^^^
TypeError: object of type 'function' has no len()
[2024-06-19 14:45:12,732] ERROR in app: Exception on /checkreview/21 [GET]
Traceback (most recent call last):
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/app/app.py", line 125, in check_review
    rew_lenth = len(reviews)
                ^^^^^^^^^^^^
TypeError: object of type 'function' has no len()
[2024-06-19 15:10:24,275] ERROR in app: Exception on /checkreview/19 [GET]
Traceback (most recent call last):
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/ve/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/std/webDev-2_2_exam/app/app.py", line 125, in check_review
    rew_lenth = len(reviews)
                ^^^^^^^^^^^^
TypeError: object of type 'function' has no len()
[2024-06-19 16:41:01 +0300] [8017] [INFO] Handling signal: term
[2024-06-19 16:41:01 +0300] [8019] [INFO] Worker exiting (pid: 8019)
[2024-06-19 16:41:01 +0300] [8017] [INFO] Shutting down: Master
[2024-06-19 16:41:02 +0300] [9441] [INFO] Starting gunicorn 22.0.0
[2024-06-19 16:41:02 +0300] [9441] [INFO] Listening at: http://127.0.0.1:5000 (9441)
[2024-06-19 16:41:02 +0300] [9441] [INFO] Using worker: sync
[2024-06-19 16:41:02 +0300] [9442] [INFO] Booting worker with pid: 9442
[2024-06-20 03:26:08 +0300] [9441] [INFO] Handling signal: term
[2024-06-20 03:26:08 +0300] [9442] [INFO] Worker exiting (pid: 9442)
[2024-06-20 03:26:08 +0300] [9441] [INFO] Shutting down: Master
[2024-06-20 03:26:10 +0300] [14857] [INFO] Starting gunicorn 22.0.0
[2024-06-20 03:26:10 +0300] [14857] [INFO] Listening at: http://127.0.0.1:5000 (14857)
[2024-06-20 03:26:10 +0300] [14857] [INFO] Using worker: sync
[2024-06-20 03:26:10 +0300] [14877] [INFO] Booting worker with pid: 14877
[2024-06-20 08:58:17 +0300] [14857] [INFO] Handling signal: term
[2024-06-20 08:58:17 +0300] [14877] [INFO] Worker exiting (pid: 14877)
[2024-06-20 08:58:18 +0300] [14857] [INFO] Shutting down: Master
[2024-06-20 08:58:19 +0300] [15376] [INFO] Starting gunicorn 22.0.0
[2024-06-20 08:58:19 +0300] [15376] [INFO] Listening at: http://127.0.0.1:5000 (15376)
[2024-06-20 08:58:19 +0300] [15376] [INFO] Using worker: sync
[2024-06-20 08:58:19 +0300] [15377] [INFO] Booting worker with pid: 15377
[2024-06-20 08:59:30 +0300] [15376] [INFO] Handling signal: term
[2024-06-20 08:59:30 +0300] [15377] [INFO] Worker exiting (pid: 15377)
[2024-06-20 08:59:30 +0300] [15376] [INFO] Shutting down: Master
[2024-06-20 08:59:31 +0300] [15437] [INFO] Starting gunicorn 22.0.0
[2024-06-20 08:59:31 +0300] [15437] [INFO] Listening at: http://127.0.0.1:5000 (15437)
[2024-06-20 08:59:31 +0300] [15437] [INFO] Using worker: sync
[2024-06-20 08:59:31 +0300] [15438] [INFO] Booting worker with pid: 15438
[2024-06-20 09:00:18 +0300] [15437] [INFO] Handling signal: term
[2024-06-20 09:00:18 +0300] [15438] [INFO] Worker exiting (pid: 15438)
[2024-06-20 09:00:18 +0300] [15437] [INFO] Shutting down: Master
[2024-06-20 09:00:19 +0300] [15508] [INFO] Starting gunicorn 22.0.0
[2024-06-20 09:00:19 +0300] [15508] [INFO] Listening at: http://127.0.0.1:5000 (15508)
[2024-06-20 09:00:19 +0300] [15508] [INFO] Using worker: sync
[2024-06-20 09:00:19 +0300] [15509] [INFO] Booting worker with pid: 15509
[2024-06-20 09:03:09 +0300] [15508] [INFO] Handling signal: term
[2024-06-20 09:03:09 +0300] [15509] [INFO] Worker exiting (pid: 15509)
[2024-06-20 09:03:10 +0300] [15508] [INFO] Shutting down: Master
[2024-06-20 09:03:11 +0300] [15583] [INFO] Starting gunicorn 22.0.0
[2024-06-20 09:03:11 +0300] [15583] [INFO] Listening at: http://127.0.0.1:5000 (15583)
[2024-06-20 09:03:11 +0300] [15583] [INFO] Using worker: sync
[2024-06-20 09:03:11 +0300] [15584] [INFO] Booting worker with pid: 15584
[2024-06-20 09:06:56 +0300] [15583] [INFO] Handling signal: term
[2024-06-20 09:06:56 +0300] [15584] [INFO] Worker exiting (pid: 15584)
[2024-06-20 09:06:57 +0300] [15583] [INFO] Shutting down: Master
[2024-06-20 09:06:58 +0300] [15635] [INFO] Starting gunicorn 22.0.0
[2024-06-20 09:06:58 +0300] [15635] [INFO] Listening at: http://127.0.0.1:5000 (15635)
[2024-06-20 09:06:58 +0300] [15635] [INFO] Using worker: sync
[2024-06-20 09:06:58 +0300] [15646] [INFO] Booting worker with pid: 15646
